CREATE TABLE [dbo].[Courses] (
    [Id]                 UNIQUEIDENTIFIER   NOT NULL,
    [CategoryId]         UNIQUEIDENTIFIER   NOT NULL,
    [CategoryName]       NVARCHAR (255)     NULL,
    [Name]               NVARCHAR (255)     NOT NULL,
    [Code]               NVARCHAR (50)      NOT NULL,
    [Type]               NVARCHAR (50)      NOT NULL,
    [ServiceProvider]    NVARCHAR (255)     NULL,
    [Description]        NVARCHAR (MAX)     NULL,
    [Duration]           INT                NOT NULL,
    [ImageName]          NVARCHAR (255)     NULL,
    [Image]              NVARCHAR (MAX)     NULL,
    [IsActivated]           BIT DEFAULT(1) NOT NULL,
    [Created]            DATETIMEOFFSET (7) NOT NULL,
    [CreatedBy]          NVARCHAR (255)     NULL,
    [CreatedByFullName]  NVARCHAR (255)     NULL,
    [Modified]           DATETIMEOFFSET (7) NOT NULL,
    [CreatedById]        UNIQUEIDENTIFIER   NULL,
    [ModifiedById]       UNIQUEIDENTIFIER   NOT NULL,
    [ModifiedBy]         NVARCHAR (255)     NULL,
    [ModifiedByFullName] NVARCHAR (255)     NULL, 
    [ServiceProviderCode]    NVARCHAR (10)     NULL,
    CONSTRAINT [PK_dbo.Courses] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Courses_Categories] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([Id]),
);

