CREATE TABLE [dbo].TrainingInvitations (
    [Id] UNIQUEIDENTIFIER NOT NULL,
	[TrainingRequestId] UNIQUEIDENTIFIER NOT NULL,
    ReferenceNumber NVARCHAR (255) NOT NULL,
	CategoryId UNIQUEIDENTIFIER NULL,
    CourseId UNIQUEIDENTIFIER  NULL,
    CourseName NVARCHAR (255)  NOT NULL,
	ServiceProvider NVARCHAR (255) NULL,
	TrainerId UNIQUEIDENTIFIER,
    TrainerName NVARCHAR (255),
	StartDate DATETIME NOT NULL DEFAULT(GETDATE()),
	EndDate DATETIME NOT NULL DEFAULT(GETDATE()),
    TotalOnlineTrainingHours INT NOT NULL DEFAULT (0),
    TotalOfflineTrainingHours INT NOT NULL DEFAULT (0),
	TrainingLocation NVARCHAR (255),
    HoursPerDay INT NOT NULL,
    NumberOfDays INT NOT NULL,
    TotalHours INT NOT NULL,
    Note NTEXT,
	AfterTrainingReportNotRequired BIT DEFAULT(0),
	AfterTrainingReportDeadline DATETIME NOT NULL DEFAULT(GETDATE()),
	Content NTEXT,
    [Status] NVARCHAR (50),
    DepartmentId UNIQUEIDENTIFIER NULL,
    DepartmentName NVARCHAR (255) NULL,
    [CreatedBySapCode]      NVARCHAR (50),
	[Created]               DATETIMEOFFSET(7) NOT NULL,
    [CreatedBy]             NVARCHAR (255),
    [CreatedByFullName]     NVARCHAR (255),
    [Modified]              DATETIMEOFFSET(7),
    [CreatedById]           UNIQUEIDENTIFIER,
    [ModifiedById]          UNIQUEIDENTIFIER NOT NULL,
    [ModifiedBy]            NVARCHAR(255),
    [ModifiedByFullName]    NVARCHAR(255),
    
    CONSTRAINT [PK_TrainingInvitations] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_TrainingInvitations_TrainingRequests] FOREIGN KEY ([TrainingRequestId]) REFERENCES [dbo].[TrainingRequests] ([Id]),
)

