CREATE TABLE [dbo].[TrainingRequests] (
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [ReferenceNumber] NVARCHAR (255) NOT NULL,
    [SapNo] NVARCHAR (255) NOT NULL,
    [Affiliate] NVARCHAR (255) NOT NULL,
	[Position] NVARCHAR (255) NOT NULL,
	[DepartmentId] UNIQUEIDENTIFIER,
    [DepartmentName] NVARCHAR (255),
    [RegionId] UNIQUEIDENTIFIER,
    [RegionName]  NVARCHAR (255),
    [DateOfSubmission] DATETIME NOT NULL DEFAULT(GETDATE()),
    [TypeOfTraining] NVARCHAR (50) NOT NULL,
	[ExistingCourse] NVARCHAR (50) NULL,
    [CategoryId] UNIQUEIDENTIFIER NULL,
    [CourseId] UNIQUEIDENTIFIER  NULL,
    [CourseName] NVARCHAR (255),
	[SupplierName] NVARCHAR (255),
	[TrainingFee] DECIMAL(25,0) DEFAULT(0),
	[ReasonOfTrainingRequest] NTEXT,
	[TrainingMethod] NVARCHAR (50) NOT NULL,
	EstimatedTrainingDays INT NOT NULL DEFAULT(0),
	EstimatedTrainingHours INT NOT NULL DEFAULT(0),
    [DepartmentInCharge]  NVARCHAR (255),
    [Year]  INT,
	ApplySponsorship BIT DEFAULT(0),
	SponsorshipPercentage INT NULL DEFAULT(0),
	WorkingCommitment BIT DEFAULT(0) NULL,
	WorkingCommitmentFrom DATETIME NULL DEFAULT null,
	WorkingCommitmentTo DATETIME NULL DEFAULT null,
	SponsorshipContractNumber  NVARCHAR (255) NULL,
	CompensateAmount DECIMAL(25,0) NULL DEFAULT(0),
	Purpose NTEXT,
	Reason NTEXT,
    [Status] NVARCHAR (MAX),
    [AssignedDepartmentId] UNIQUEIDENTIFIER,
    [AssignedDepartmentName] NVARCHAR (255),
    [AssignedDepartmentGroup] INT,
    [AssignedDepartmentPosition] NVARCHAR (255),
    [AssignedUserId] NVARCHAR (Max),
    [WorkflowStep] INT,
    [WorkflowData] NVARCHAR (MAX),
    [DueDate] DATETIMEOFFSET(7),
    [Created] DATETIMEOFFSET(7) NOT NULL,
    [CreatedBy] NVARCHAR (255),
    [CreatedByFullName] NVARCHAR (255),
    [Modified] DATETIMEOFFSET(7),
    [CreatedById] UNIQUEIDENTIFIER,
    [ModifiedById] UNIQUEIDENTIFIER NOT NULL,
    [ModifiedBy] NVARCHAR(255),
    [ModifiedByFullName] NVARCHAR(255),
    [HowApply] NTEXT,
    [WhenExcute] NTEXT,
    [WhatExpectedKPI] NTEXT,
    [ActualTuitionReimbursementAmount] DECIMAL(13),
    [From] DATETIME NULL, 
    [To] DATETIME NULL, 
    [F2ReferenceNumber] NVARCHAR(255) NULL, 
    [F2URL] NVARCHAR(255) NULL, 
    [RequestedDepartment] NVARCHAR(255) NULL, 
    [RequestedDepartmentCode] NVARCHAR(50) NULL, 
    [DepartmentInChargeCode] NVARCHAR(50) NULL, 
    [SupplierCode] NVARCHAR(50) NULL, 
    [MethodOfChoosingContractor] NVARCHAR(255) NULL, 
    [TheProposalFor] NVARCHAR(255) NULL, 
    [Reference] NVARCHAR(255) NULL, 
    [RequestedDepartmentId] UNIQUEIDENTIFIER NULL, 
    [DepartmentInChargeId] UNIQUEIDENTIFIER NULL, 
    [DicDepartmentCode] NVARCHAR(255) NULL, 
    CONSTRAINT [PK_dbo.TrainingRequests] PRIMARY KEY CLUSTERED ([Id] ASC)
);

