CREATE TABLE [dbo].[TrainingReports] (
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [ReferenceNumber] NVARCHAR (255) NOT NULL,
    [SapCode] NVARCHAR(50) NOT NULL,
    [FullName] NVARCHAR(255) NOT NULL,
    [Location] NVARCHAR(255) NULL,
    [DepartmentId] UNIQUEIDENTIFIER NULL,
    [DepartmentName] NVARCHAR (255) NULL,
    [RegionId] UNIQUEIDENTIFIER NULL,
    [RegionName] NVARCHAR (255) NULL,
    [Position] NVARCHAR(255) NULL,
    [TrainingInvitationId] UNIQUEIDENTIFIER NOT NULL,
    [TrainerName]           NVARCHAR (255) NOT NULL,
    [OtherReasons]          NTEXT,
    [OtherFeedback]         NTEXT,
    [Remark]                NTEXT,
    [Status]                NVARCHAR (255),
    [AssignedDepartmentId]  UNIQUEIDENTIFIER,
    [AssignedDepartmentName]NVARCHAR (255),
    [AssignedDepartmentGroup] INT,
    [AssignedDepartmentPosition] NVARCHAR (255),
    [AssignedUserId]        NVARCHAR (Max),
    [WorkflowStep]          INT,
    [WorkflowData]          NVARCHAR (MAX),
    [DueDate]               DATETIMEOFFSET(7),
    [Created]               DATETIMEOFFSET(7) NOT NULL,
    [CreatedBy]             NVARCHAR (255),
    [CreatedByFullName]     NVARCHAR (255),
    [Modified]              DATETIMEOFFSET(7),
    [CreatedById]           UNIQUEIDENTIFIER,
    [ModifiedById]          UNIQUEIDENTIFIER NOT NULL,
    [ModifiedBy]            NVARCHAR(255),
    [ModifiedByFullName]    NVARCHAR(255),
    [ActualAttendingDate]   DATETIME NULL,
    CONSTRAINT [PK_dbo.TrainingReports] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TrainingReports_TrainingInvitations] FOREIGN KEY ([TrainingInvitationId]) REFERENCES [dbo].[TrainingInvitations] ([Id]),
)

