# Tên của workflow
name: Auto Create Branch From Issue

# Cấu hình khi nào workflow sẽ được kích hoạt
on:
  issues:
    types: [opened, labeled]

# Các công việc cần thực hiện
jobs:
  create_branch_job:
    runs-on: ubuntu-latest
    
    steps:
      # Bước 1: Xác định tiền tố cho nhánh dựa trên nhãn của issue
      - name: Determine Branch Prefix
        id: get_prefix
        run: |
          LABELS_JSON='${{ toJSON(github.event.issue.labels.*.name) }}'
          PREFIX="chore/"
          
          if [[ $(echo "$LABELS_JSON" | grep -i "bug") ]]; then
            PREFIX="fix/"
          elif [[ $(echo "$LABELS_JSON" | grep -i "feature") ]]; then
            PREFIX="feature/"
          elif [[ $(echo "$LABELS_JSON" | grep -i "documentation") ]]; then
            PREFIX="docs/"
          fi
          
          echo "prefix=$PREFIX" >> $GITHUB_OUTPUT

      # Bước 2: Sử dụng Action từ Marketplace để tạo nhánh (ĐÃ SỬA LỖI)
      - name: Create Branch From Issue
        # Sửa tên action ở dòng này
        uses: robot-actions/create-branch-when-issue-created@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch-name: '${{ steps.get_prefix.outputs.prefix }}{issue-number}-{issue-title}'
