# Tên của workflow, hiển thị trong tab "Actions" trên GitHub
name: Auto Create Branch From Issue

# Cấu hình sự kiện kích hoạt workflow
on:
  # Chạy khi một issue được MỞ hoặc được GÁN NHÃN
  issues:
    types: [opened, labeled]

# Nơi định nghĩa các công việc cần thực hiện
jobs:
  # Đặt tên cho công việc là 'create_branch_job'
  create_branch_job:
    # Luôn chạy trên phiên bản Ubuntu mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest
    
    # Các bước tuần tự mà công việc sẽ thực hiện
    steps:
      # Bước 1: Quyết định tiền tố cho branch (ví dụ: 'fix/' hoặc 'feature/')
      - name: Determine Branch Prefix
        # Đặt một ID cho bước này để các bước sau có thể tham chiếu đến kết quả của nó
        id: get_prefix
        # Chạy một đoạn mã shell script
        run: |
          # Lấy danh sách các label của issue dưới dạng một chuỗi JSON
          LABELS_JSON='${{ toJSON(github.event.issue.labels.*.name) }}'
          
          # Đặt tiền tố mặc định là 'chore/' cho các công việc nhỏ, không phân loại
          PREFIX="chore/"
          
          # Dùng câu lệnh 'grep' để kiểm tra sự tồn tại của các từ khóa trong chuỗi label
          if [[ $(echo "$LABELS_JSON" | grep -i "bug") ]]; then
            PREFIX="fix/"
          elif [[ $(echo "$LABELS_JSON" | grep -i "feature") ]]; then
            PREFIX="feature/"
          elif [[ $(echo "$LABELS_JSON" | grep -i "documentation") ]]; then
            PREFIX="docs/"
          fi
          
          # Xuất biến PREFIX ra để các bước sau có thể sử dụng
          echo "prefix=$PREFIX" >> $GITHUB_OUTPUT

      # Bước 2: Sử dụng một Action có sẵn để thực hiện việc tạo branch
      - name: Create Issue Branch
        # Tên action mới và chính xác, đang hoạt động ổn định
        uses: andymckay/create-issue-branch@v1
        with:
          # Cung cấp token mặc định của GitHub để action có quyền tạo branch trong repo của bạn
          token: ${{ secrets.GITHUB_TOKEN }}
          # Định dạng tên nhánh sẽ được tạo ra
          # Action này sẽ tự động dọn dẹp tiêu đề issue (thay khoảng trắng bằng '-', xóa ký tự đặc biệt)
          # Ví dụ: 'fix/123-login-button-is-broken'
          branchName: '${{ steps.get_prefix.outputs.prefix }}${{ github.event.issue.number }}-${{ github.event.issue.title }}'
